### ISSUE TITLE
COM library memory leak

### ISSUE THREAD

**Issue by rodrigocfd** [anatawa12/vrc-log-renamer#12]
There are two memory leaks in `task_manager.rs`.

Every call to [`CoInitializeEx`](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex) allocates memory, which must be freed by a matching [`CoUninitialize`](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-couninitialize), which is not happening – and it's called in two different points.

That's why it's preferable to use WinSafe whenever possible, because it takes care of all that stuff. Its [`CoInitializeEx`](https://rodrigocfd.github.io/winsafe/winsafe/fn.CoInitializeEx.html) implementation will return a guard that will take care of the cleanup.

**Comment by anatawa12** [comment]
Thank you for adding wrappers for ITaskService and telling me! I'm going to use the api instead.
