### ISSUE TITLE
LICENSE ファイルがない

### ISSUE THREAD

**Issue by kobi32768** [anatawa12/vrc-log-renamer#2]
Booth によると GPL-3.0 と思われるが GitHub に LICENSE ファイルが置かれていない

**Comment by kobi32768** [comment]
`/` にないだけっぽい？

**Comment by anatawa12** [comment]
/にないのは意図的にそうしてます。それぞれのフォルダにあるライブラリとして使える部分にはMITを、アプリ本体にはGPL 3.0を適用させてます。

**Comment by kobi32768** [comment]
👌
