### ISSUE TITLE
出力形式が `%3f` に対応していない

### ISSUE THREAD

**Issue by kobi32768** [anatawa12/vrc-log-renamer#5]
`%.3f` では通るが `%3f` ではフォーマットが不正とエラーが出る
![image](https://user-images.githubusercontent.com/40712426/201501685-59bd9691-c382-458c-a802-2e27388766e0.png)
![image](https://user-images.githubusercontent.com/40712426/201501736-95d5347a-90bc-4421-939b-ec1bb4c0c85d.png)

**Comment by anatawa12** [comment]
技術的な理由で実装が面倒であったため需要が低い(というかない)と判断して実装してませんでしたがctimeを使用可能にしたため実装します。 https://docs.rs/chrono/latest/src/chrono/format/strftime.rs.html#446-457
