### ISSUE TITLE
移動すると作成日時が失なわれる

### ISSUE THREAD

**Issue by kobi32768** [anatawa12/vrc-log-renamer#6]
移動後ファイルの作成日時を元ファイルと同じになるようにしてほしい

あるいは、rename して複製されたファイルとは別に元のログファイルを別のディレクトリに移動させるオプションがほしい

**Comment by anatawa12** [comment]
Keep Originalをオフにすると同一ファイルシステム内である場合にはファイル移動で処理されるため作成日時が保存されると思います。
また、コピーの状態でもctime・mtimeを保存されるように変更しました。
